---
micronaut:
  application:
    name: micro
  server:
        port: 8080
        cors:
            enabled: true

---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/healthcare
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'virtue909'
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
    datasources: 
        default: 
            locations: classpath:dbmigrations 

endpoints:
    flyway:
        enabled: true 
        sensitive: false 