---
micronaut:
  application:
    name: micro
  server:
    port: 8081
    cors:
      enabled: true
---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/praxis
    driverClassName: org.postgresql.Driver
    username: postgres
    password: "warouw1945"
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      locations: classpath:dbmigrations

endpoints:
  flyway:
    enabled: true
    sensitive: false
